services:
  app:
    container_name: express-ts-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/express-ts-prisma
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    restart: unless-stopped

  mongodb:
    container_name: express-ts-mongodb-dev
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
